name: Build and Deploy to Azure

on:
    push:
        branches: [master]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Azure
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Log in to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: flowaiacr.azurecr.io
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Build and push Docker image
              run: |
                  docker build -t flowaiacr.azurecr.io/flowaiapi:latest .
                  docker push flowaiacr.azurecr.io/flowaiapi:latest

            - name: Restart App Service to pull new image
              run: |
                  az webapp restart \
                    --name flow-ai-api \
                    --resource-group rg-veervs19-7627_ai
